# Generated by Django 4.1.4 on 2022-12-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='placename',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
