# Generated by Django 4.1.4 on 2022-12-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_address_placename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_destination',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_origin',
        ),
        migrations.AddField(
            model_name='address',
            name='lat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='lng',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
