# Generated by Django 4.1.4 on 2022-12-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_address_is_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
