# Generated by Django 4.1.4 on 2022-12-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_address_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
