# Generated by Django 4.1.4 on 2022-12-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_address_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city_crime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='address',
            name='foot_traffic_data',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='address',
            name='nation_crime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='address',
            name='state_crime',
            field=models.IntegerField(default=0),
        ),
    ]
