# Generated by Django 4.1.4 on 2022-12-29 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_address_city_crime_address_foot_traffic_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='foot_traffic_data',
            new_name='foot_traffic',
        ),
    ]
