# Generated by Django 4.1.4 on 2022-12-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_foot_traffic_data_address_foot_traffic'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='avg_gas',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='foot_traffic',
            field=models.TextField(null=True),
        ),
    ]
