# Generated by Django 4.1.4 on 2022-12-30 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_address_avg_gas'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='last_update',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='address',
            name='avg_gas',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
