# Generated by Django 4.1.4 on 2022-12-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_address_last_update_alter_address_avg_gas'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='last_origin_id',
            field=models.IntegerField(null=True),
        ),
    ]
